import {ConceptResponse} from "@/services/types/concept";
import {SliderResponse} from "@/services/types/slider";
import {SpecialProductResponse} from "@/services/types/specialProduct";
import {HomepageCategoryResponse} from "@/services/types/homepageCategory";
import {PopularProductResponse} from "@/services/types/popularProduct";
import {BrandResponse} from "@/services/types/brand";
import {NewsResponse} from "@/services/types/news";
import {BannerResponse} from "@/services/types/banner";
import {VlogResponse} from "@/services/types/vlog";
import {PosterResponse} from "@/services/types/poster";
import {TrustedBrandResponse} from "@/services/types/trustedBrand";
import {CampaignResponse} from "@/services/types/campaign";
import {CampaignBannerResponse} from "@/services/types/campaignBanner";
import {DiscountItemResponse} from "@/services/types/discountItem";

export type HomePageResponse = {
    popularProducts: { data: PopularProductResponse[] };
    discount: DiscountItemResponse;
    campaign?: CampaignResponse;
    pending_campaign?: CampaignResponse;
    banners: { data: BannerResponse[] };
    banners2: { data: BannerResponse[] };
    banners3: { data: BannerResponse[] };
    banners4: { data: BannerResponse[] };
    bannersStock: { data: BannerResponse[] };
    banners5: { data: BannerResponse[] };
    homepageCategories: { data: HomepageCategoryResponse[] };
    desktopSliders: { data: SliderResponse[] };
    mobileSliders: { data: SliderResponse[] };
    homepageBanner: { data: CampaignBannerResponse[] };
    homepage2Banner: { data: CampaignBannerResponse[] };
    brands: { data: BrandResponse[] };
    trustedBrands: { data: TrustedBrandResponse[] };
    news: { data: NewsResponse[] };
    vlogs: { data: VlogResponse[] };
    posters: { data: PosterResponse[] };
    concepts: { data: ConceptResponse[] };
    specialProducts: { data: SpecialProductResponse[] };
};
